# Generated by Django 4.1.1 on 2025-01-19 22:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('f_fabricacion', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2015, 1, 1))], verbose_name='Fecha de fabricación')),
                ('p_costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de costo')),
                ('p_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de venta')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='laboratorio.laboratorio', verbose_name='Laboratorio fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('laboratorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_general', to='laboratorio.laboratorio', verbose_name='Laboratorio asociado')),
            ],
        ),
    ]
